import { useState, useEffect } from 'react';
import axios from 'axios';
import { Users, Activity, IndianRupee, PieChart, TrendingUp, CalendarDays, Download } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';
import DashboardLayout from '../components/DashboardLayout';
import { jsPDF } from 'jspdf';

const AdminDashboard = () => {
  const [stats, setStats] = useState({
    totalPatients: 0,
    activeTokens: 0,
    totalRevenue: 0,
    staffCount: 3
  });

  const revenueData = [
    { name: 'Mon', revenue: 4000 },
    { name: 'Tue', revenue: 3000 },
    { name: 'Wed', revenue: 2000 },
    { name: 'Thu', revenue: 2780 },
    { name: 'Fri', revenue: 1890 },
    { name: 'Sat', revenue: 2390 },
    { name: 'Sun', revenue: 3490 },
  ];

  useEffect(() => {
    const fetchStats = async () => {
      try {
        const patientsRes = await axios.get('/patients');
        const tokensRes = await axios.get('/tokens');
        
        setStats(prev => ({
          ...prev,
          totalPatients: patientsRes.data.data.length || 0,
          activeTokens: tokensRes.data.data.filter(t => t.status !== 'Completed').length || 0,
          totalRevenue: 5400
        }));
      } catch (e) {
        console.error(e);
      }
    };
    fetchStats();
  }, []);

  const downloadReport = () => {
    try {
      const doc = new jsPDF();
      
      // Title
      doc.setFontSize(24);
      doc.setTextColor(37, 99, 235);
      doc.text('ClinicCare Hub', 105, 22, { align: 'center' });
      
      doc.setFontSize(11);
      doc.setTextColor(120, 120, 120);
      doc.text('Admin Dashboard Report', 105, 30, { align: 'center' });
      doc.text('Generated: ' + new Date().toLocaleString(), 105, 36, { align: 'center' });
      
      // Divider
      doc.setDrawColor(200);
      doc.line(20, 42, 190, 42);
      
      // Table header
      const startY = 52;
      const rowH = 12;
      doc.setFillColor(37, 99, 235);
      doc.rect(20, startY, 170, rowH, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      doc.text('Metric', 25, startY + 8);
      doc.text('Value', 130, startY + 8);
      
      // Table rows
      const rows = [
        ['Total Patients Registered', String(stats.totalPatients)],
        ['Active Queue Tokens', String(stats.activeTokens)],
        ['Estimated Daily Revenue', 'INR ' + String(stats.totalRevenue)],
        ['Staff Members Online', String(stats.staffCount)],
      ];
      
      doc.setFont(undefined, 'normal');
      rows.forEach((row, i) => {
        const y = startY + rowH + (i * rowH);
        if (i % 2 === 0) {
          doc.setFillColor(245, 247, 250);
          doc.rect(20, y, 170, rowH, 'F');
        }
        doc.setTextColor(50, 50, 50);
        doc.text(row[0], 25, y + 8);
        doc.setTextColor(37, 99, 235);
        doc.setFont(undefined, 'bold');
        doc.text(row[1], 130, y + 8);
        doc.setFont(undefined, 'normal');
      });
      
      // Border around table
      doc.setDrawColor(200);
      doc.rect(20, startY, 170, rowH + (rows.length * rowH));
      
      // Footer
      const footY = startY + rowH + (rows.length * rowH) + 25;
      doc.setTextColor(150);
      doc.setFontSize(9);
      doc.text('This report was auto-generated by ClinicCare Hub Management System.', 105, footY, { align: 'center' });
      
      // Download as blob
      const pdfBlob = doc.output('blob');
      const blobUrl = window.URL.createObjectURL(pdfBlob);
      const a = document.createElement('a');
      a.style.display = 'none';
      a.href = blobUrl;
      a.download = 'Admin_Report.pdf';
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(blobUrl);
      document.body.removeChild(a);
    } catch (err) {
      console.error('PDF Error:', err);
      window.alert('PDF Error: ' + err.message);
    }
  };

  return (
    <DashboardLayout>
      <div className="space-y-6 sm:space-y-8 animate-fade-in pb-10">
        
        {/* Header section */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-gray-900 tracking-tight">System Overview</h2>
            <p className="text-gray-500 mt-1 flex items-center gap-2 text-sm sm:text-base">
              <CalendarDays size={16}/> {new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>
          <button 
            onClick={downloadReport}
            className="w-full sm:w-auto hover:opacity-90 text-white font-medium py-2.5 px-6 rounded-lg shadow-sm transition-opacity flex items-center justify-center gap-2 transform active:scale-95" 
            style={{backgroundColor: '#2563EB'}}
          >
            <Download size={18}/> Download Full Report
          </button>
        </div>

        {/* Top Stat Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6">
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 flex items-center gap-5 hover:border-blue-200 transition-all">
            <div className="bg-blue-100 p-4 rounded-full text-blue-600 shrink-0">
              <Users size={28} />
            </div>
            <div className="min-w-0">
              <p className="text-sm font-medium text-gray-500 uppercase tracking-wider truncate">Total Patients</p>
              <h3 className="text-2xl sm:text-3xl font-bold text-gray-900">{stats.totalPatients}</h3>
              <p className="text-xs text-green-600 font-medium mt-1 flex items-center truncate"><TrendingUp size={12} className="mr-1 shrink-0"/> +12% this week</p>
            </div>
          </div>
          
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 flex items-center gap-5 hover:border-yellow-200 transition-all text-sm sm:text-base">
            <div className="bg-yellow-100 p-4 rounded-full text-yellow-600 shrink-0">
              <Activity size={28} />
            </div>
            <div className="min-w-0">
              <p className="text-sm font-medium text-gray-500 uppercase tracking-wider truncate">Active Tokens</p>
              <h3 className="text-2xl sm:text-3xl font-bold text-gray-900">{stats.activeTokens}</h3>
              <p className="text-xs text-yellow-600 font-medium mt-1 flex items-center truncate">Live current queue</p>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 flex items-center gap-5 hover:border-green-200 transition-all">
            <div className="bg-green-100 p-4 rounded-full text-green-600 shrink-0">
              <IndianRupee size={28} />
            </div>
            <div className="min-w-0">
              <p className="text-sm font-medium text-gray-500 uppercase tracking-wider truncate">Daily Revenue</p>
              <h3 className="text-2xl sm:text-3xl font-bold text-gray-900">₹{stats.totalRevenue}</h3>
              <p className="text-xs text-green-600 font-medium mt-1 flex items-center truncate"><TrendingUp size={12} className="mr-1 shrink-0"/> +5% today</p>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 flex items-center gap-5 hover:border-purple-200 transition-all">
            <div className="bg-purple-100 p-4 rounded-full text-purple-600 shrink-0">
              <Users size={28} />
            </div>
            <div className="min-w-0">
              <p className="text-sm font-medium text-gray-500 uppercase tracking-wider truncate">Staff Online</p>
              <h3 className="text-2xl sm:text-3xl font-bold text-gray-900">{stats.staffCount}</h3>
              <p className="text-xs text-gray-500 font-medium mt-1 flex items-center truncate">Active sessions</p>
            </div>
          </div>
        </div>

        {/* Charts and Footer */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 pb-6">
          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4 sm:p-6">
             <h3 className="text-lg font-bold text-gray-800 mb-6 flex items-center gap-2">
              <IndianRupee size={20} className="text-green-500" /> Weekly Revenue Trend
            </h3>
            <div className="h-64 sm:h-72 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={revenueData}>
                  <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f0f0f0"/>
                  <XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fontSize: 12}} />
                  <YAxis axisLine={false} tickLine={false} tick={{fontSize: 12}} />
                  <Tooltip cursor={{fill: '#f8fafc'}} contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 12px rgba(0,0,0,0.05)'}} />
                  <Bar dataKey="revenue" fill="#3b82f6" radius={[4, 4, 0, 0]} maxBarSize={35} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>

          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-4 sm:p-6">
            <h4 className="font-bold text-gray-800 mb-4 uppercase text-xs tracking-widest text-gray-400">Quick Actions</h4>
            <div className="grid grid-cols-1 gap-3">
               <div className="p-4 border border-gray-100 rounded-xl bg-gray-50 hover:bg-white hover:shadow-sm transition-all cursor-pointer">
                  <p className="font-bold text-sm text-gray-800">Manage Staff Accounts</p>
                  <p className="text-xs text-gray-500">Add, edit or disable system users</p>
               </div>
               <div className="p-4 border border-gray-100 rounded-xl bg-gray-50 hover:bg-white hover:shadow-sm transition-all cursor-pointer">
                  <p className="font-bold text-sm text-gray-800">Clinic Settings</p>
                  <p className="text-xs text-gray-500">Configure clinic name, logo and departments</p>
               </div>
               <div className="p-4 border border-gray-100 rounded-xl bg-gray-50 hover:bg-white hover:shadow-sm transition-all cursor-pointer">
                  <p className="font-bold text-sm text-gray-800">Data Backup</p>
                  <p className="text-xs text-gray-500">Export clinical data to CSV/JSON</p>
               </div>
            </div>
          </div>
        </div>

      </div>
    </DashboardLayout>
  );
};

export default AdminDashboard;
